name: Deploy to Production

on:
  push:
    branches: [main]
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '.github/workflows/ci.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to VPS
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          # Create SSH key file
          mkdir -p ~/.ssh
          echo "$DEPLOY_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          
          # Add host to known_hosts
          ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts 2>/dev/null
          
          # Deploy via SSH
          ssh -i ~/.ssh/deploy_key $DEPLOY_USER@$DEPLOY_HOST << 'EOF'
            cd $DEPLOY_PATH
            
            # Pull latest code
            git fetch origin main
            git reset --hard origin/main
            
            # Install dependencies
            npm ci --only=production
            
            # Run database migrations
            npm run migrate || true
            
            # Restart services
            sudo systemctl restart insta-connect-app
            sudo systemctl restart token-refresh
            sudo systemctl restart webhook-processor
            
            # Verify deployment
            sleep 5
            curl -f http://localhost:3000/health || exit 1
            
            echo "✅ Deployment successful"
          EOF

      - name: Notify deployment
        if: success()
        run: |
          echo "✅ Production deployment completed successfully"
          echo "Application: https://insta.tiblings.com"

      - name: Notify failure
        if: failure()
        run: |
          echo "❌ Production deployment failed"
          exit 1

